package com.arobs.enums;

public enum PesticideType {
    ACARICIDE  ,
    HERBICIDE ,
    FUNGICIDE ,
    INSECTOFUNGICIDE ,
    GROWTH_REGULATION ,
    DEFOLIANT_DESICCANT ,
    PHEROMONE ,
    INSECTICIDE ,
    NEMATOCIDE_SOIL_DESINFECTANT ,
    MISCELLANEOUS_AUXILIARY_PRODUCT ,
    RODENTICIDE_MOLLUSCICIDE_REPELLANT ;


}