INSERT INTO county (country_id, id, name_ro, name_ru) VALUES
('MD','AN','r-nul Anenii Noi','Новоаненский район‎'),
('MD','BS','r-nul Basarabeasca','Бессарабский район'),
('MD','BL','or.Bălți','Бельцы'),
('MD','BE','or.Bender tr.','Бендеры'),
('MD','BR','r-nul Briceni','Бричанский район‎'),
('MD','CH','r-nul Cahul','Кагульский район‎'),
('MD','CC','r-nul Camenca tr.','Каменский район‎'),
('MD','CT','r-nul Cantemir','Кантемирский район‎'),
('MD','CL','r-nul Călărași','Каларашский район‎'),
('MD','CS','r-nul Căușeni','Каушанский район‎'),
('MD','CG','r-nul Ceadîr-Lunga','Чадыр-Лунгский район‎'),
('MD',' C', 'mun.Chișinău','Кишинев'),
('MD','CM','r-nul Cimișlia','Чимишлийский район‎'),
('MD','CO','r-nul Comrat','Комратский район‎'),
('MD','CR','r-nul Criuleni','Криулянский район‎'),
('MD','DN','r-nul Dondușeni','Дондюшанский район‎'),
('MD','DR','r-nul Drochia','Дрокиевский район‎'),
('MD','DB','r-nul Dubăsari','Дубоссарский район'),
('MD','ED','r-nul Edineț','Единецкий район‎'),
('MD','FL','r-nul Fălești','Фалештский район‎'),
('MD','FR','r-nul Florești','Флорештский район‎'),
('MD','GL','r-nul Glodeni','Глодянский район‎'),
('MD','GR','r-nul Grigoriopol tr.','Григориопольский район‎'),
('MD','HN','r-nul Hîncești','Хынчештский район‎'),
('MD','IL','r-nul Ialoveni','Яловенский район‎'),
('MD','LV','r-nul Leova','Леовский район‎'),
('MD','NS','r-nul Nisporeni','Ниспоренский район‎'),
('MD','OC','r-nul Ocnița','Окницкий район‎'),
('MD','OR','r-nul Orhei','Оргеевский район‎'),
('MD','RZ','r-nul Rezina','Резинский район‎'),
('MD','RB','r-nul Rîbnița tr.','Рыбницкий район‎'),
('MD','RS','r-nul Rîșcani','Рышканский район‎'),
('MD','SG','r-nul Sîngerei','Сынжерейский район‎'),
('MD','SL','r-nul Slobozia tr.','Слободзейский район‎'),
('MD','SR','r-nul Soroca','Сорокский район‎'),
('MD','ST','r-nul Strășeni','Страшенский район‎'),
('MD','SD','r-nul Șoldănești','Шолданештский район‎'),
('MD','SV','r-nul Ștefan Vodă','Штефан-Водский район‎'),
('MD','TR','r-nul Taraclia','Тараклийский район‎'),
('MD','TL','r-nul Telenești','Теленештский район‎'),
('MD','TS','or.Tiraspol tr.','Тирасполь'),
('MD','UN','r-nul Ungheni','Унгенский район‎');

INSERT INTO country (id, name_ro, name_ru) VALUES
('MD', 'Moldova', 'Молдова'),
('RO', 'România', 'Румыния');