INSERT INTO crop_variety(id, crop_id, crop_subculture_id, name_ro, name_ru, description_ro) VALUES 
(1, 1, 1, 'AKTEUR', 'АКТЕР', 'Cel mai cunoscut soi de grau din generatia noua, Akteur si-a capatat notorietatea in randul cultivatorilor datorita rezultatelor foarte bune, in special din Banat, Crisana si centrul tarii. Este un soi nearistat, care performeaza pe toate tipurile de sol (inclusiv pe cele din zonele secetoase) si este recunoscut pentru toleranta crescuta fata de boli si calitatea recoltei ELITA (excelent pentru panificatie). Este cel mai tardiv soi din portofoliu, fiind pretabil pentru semanatul in afara epocii datorita dezvoltarii puternice in toamna. Nu se recomanda semanatul timpuriu deoarece poate conduce la slabirea tolerantei la ger. Poate asigura un nivel ridicat de productivitate in conditii tehnologice foarte variate, datorita calitatii superioare a recoltei recomandam aplicarea unei tehnologii intensive. Potentialul ridicat de productie trebuie sustinut cu un nivel ridicat de fertilizare si tratament cu fungicid. Foliajul este abundet, lat si lax cu continut ridicat de pruina pana spre finalul perioadei de vegetatie. In plus, are un sistem radicular bine dezvoltat, iar paiul este viguros si foarte tolerant la inclinare si frangere.'),
(2, 1, 1, 'ARKTIS', 'АРКТИС', 'Soi nearistat de mare productivitate, cu talia medie-inalta (80-100 cm), caracterizat de calitatea superioara a indicilor recoltei - ELITA (excelent pentru panificatie), precum si pentru randamentul foarte mare al fainii. Este de maturare intermediara, in 2016 procesul de inflorire declansandu-se in jurul perioadei 16-18 mai. Raspunde foarte bine in conditii de tehnologie intensiva, iar plasticitatea ecologica il recomanda pentru toate zonele de cultura a cerealelor paioase.'),
(3, 1, 1, 'XERXES', 'КСЕРКС',  'Soi timpuriu, nearistat, cu o buna adaptare pedoclimatica. Este de asemenea un soi cu o calitate superioara a recoltei, din categoria ELITA (recomandat pentru morarit si panificatie). Are cea mai inalta talie din portofoliul Biocrop (circa 100-120 cm) si este caracterizat de continutul superior de gluten umed. In plus, este foarte rezistent la ger, inclinare si frangere, iar toleranta buna fata de principalele boli foliare il recomanda pentru conditiile medii de tehnologie.'),
(4, 1, 1, 'PATRAS', 'Патры', 'Soi de maturitate intermediara, nearistat, caracterizat prin rezistenta foarte mare la conditii de iarna si potentialul de productie ridicat. Foliajul este semierect cu o prezenta ridicata a pruinei. Spicele sunt nearistate, laxe, iar talia este medie de aproximativ 80-90 cm. Soiul si-a dobandit aprecierea datorita nivelului stabil al productivitatii, in special in zona Moldovei si Olteniei. Se incadreaza in grupa de calitate “A” si are de asemenea o foarte buna rezistenta la boli, inclinare si frangere.'),
(5, 1, 2, 'COMBIN', 'Совмещенный', 'Este cel mai nou soi din portofoliul Biocrop, singurul aristat si cu cea mai joasa talie (circa 80 cm). Este de maturitate timpurie, cu o calitate a recoltei care se incadreaza in parametrii de ELITA (conform clasificarilor germane) - are capacitatea genetica de a dobandi indici foarte buni pentru panificatie intr-o tehnologie specifica. In plus, datorita tolerantei ridicate la bolile foliare specifice, recoltele sunt foarte stabile. Este unul din cele mai solicitate soiuri de grau in Campania 2016/2017, bucurandu-se de aprecierea cultivatorilor care l-au recoltat pentru prima oara in 2016. Soiul este recomandat in toate conditiile de cultivare, poate valorifica prin cantitatea si calitatea recoltei tehnologiile intensive.'),
(6, 1, 2, 'POTENZIAL', 'ПОТЕНЦИАЛ', 'Soi nearistat de maturitate semi-tardiva, caracterizat prin buna plasticitate ecologica si nivelul ridicat de productivitate in conditii dificile, valorificand foarte bine solurile sarace. Are o buna toleranta fata de principalele boli. Talia este medie, iar aparatul foliar este semierect. La maturitate, ca si la restul cerealelor paioase din portofoliu, spicul capata o forma curbata care nu favorizeaza stagnarea apei si astfel se previne deprecierea calitatii recoltei. Este un sortiment de grau cu un randament ridicat. Prezinta o rezistenta buna la seceta si ger, iar clasa A de calitate ii asigura un continut ridicat si stabil de proteina.'),
(7, 1, 2, 'ATTRAKTION', 'аттракцион', 'Soi semi-timpuriu, nearistat, cu cea mai buna toleranta fata de bolile foliare intre soiurile din portofolioul Biocrop. S-a remarcat prin stabilitate productiva foarte ridicata, indiferent de arealul de cultura (in top 3 productii). Este un soi capabil sa dobandeasca indici de panificatie din categoria A si poate valorifica prin productie o tehnologie intensiva. Este caracterizat de un foliaj abundent, lat, lax, precum si de stabilitatea indicelul de cadere, rezistenta la inclinare si frangere si toleranta crescuta fata de boli.'),
(8, 1, 2, 'CHEVALIER', 'рыцарь', 'Este un soi cu maturitate la recoltare semi-tardiva, din categoria “A” de calitate a recoltei. Este nearistat, de talie a plantei de cca. 20 cm, cu foliaj lax, Alaturi de Potenzial este unul din soiurile cele mai cunoscute si apreciate de cultivatorii parteneri. A demonstrat un nivel stabil, sporit al productiilor, in special in Muntenia, Oltenia si Moldova. De asemenea, prezinta un continut ridicat si stabil de proteina. Este un soi stabil, foarte rezistent in conditii de ger si seceta, putand si cultivat si dupa porumb.');

UPDATE crop_variety SET description_ru = description_ro WHERE id BETWEEN 1 AND 8;

SELECT setval('crop_variety_id_seq', (SELECT MAX(id) FROM crop_variety));
